---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность регистрации на сайте
  - Пользователь должен иметь возможность аутентификации
  - Поиск товара должен быть доступен на любой странице
  - Возможен выбор категорий и подкатегорий товаров
  - Товар можно выбрать по нескольким критериям
  - Доступ к категориям возможен на любой странице
  - При выборе категории - отображаются товары из этой категории
  - При клике на товар можно перейти на детальную страницу с возможностью сравнения с другим товаром этой же категории
  - При нажатии на кнопку добавить в корзину - выводится сообщение об успешном добавлении
  - Есть ссылка возврата к предыдущему разделу на любой стринице, кроме главной
  - Добавив товар в корзину, пользователь может сразу перейти к оформлению
  - Максимально уменшить вес страницы, для более быстрой загрузки
  - Страница должна быть защищена по протоколу HTTPS
  - Экранировать символы в полях ввода
  - Сайт должен быть адаптирован под мобильные устройства
  - Сайт должен быть кроссбраузерным
  - Сайт должен быть адаптивным
