---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен иметь мобильную версию
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность регистрации на сайте
  - Пользователь должен иметь возможность аутентификации
  - Поиск товара должен быть доступен на любой странице
  - Возможен выбор категорий и подкатегорий товаров
  - Товар можно выбрать по нескольким критериям
  - Доступ к категориям возможен на любой странице
  - При выборе категории - отображаются товары из выбранной категории
  - При клике на товар можно перейти на детальную страницу с возможностью сравнения с другим товаром этой же категории
  - При нажатии на кнопку добавить в корзину - выводится сообщение об успешном добавлении
  - Есть ссылка возврата к предыдущему разделу на каждой стринице, кроме главной
  - Добавив товар в корзину, на этой же странице пользователь может сразу перейти к оформлению
  - У сайта должен быть минимальный вес страницы, для более быстрой загрузки
  - Страница должна быть защищена по протоколу HTTPS
  - У сайта должна быть функция экранирования символов в полях ввода
  - Сайт должен быть адаптирован под мобильные устройства
  - Сайт должен работать в разных браузерах
  - Сайт должен поддерживать автоматическое изменение страницы в зависимости от размера экрана пользователя
  - На странице должны отображаться сразу все категории и производители
