---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность регистрации на сайте
  - Пользователь должен иметь возможность аутентификации
  - Поиск товара должен быть доступен на любой странице
  - Возможен выбор категорий и подкатегорий товаров
  - Товар можно выбрать по нескольким критериям
  - Доступа к категориям возможен на любой странице
  - При выборе категории - отображаются товары из этой категории
  - При клике на товар можно перейти на детальную страницу с подробным описанием
  - При нажатии на кнопку добавить в корзину - выбранный товар будет отображаться в корзине
  - Должна быть реализована возможность возврата на предыдущий шаг, на странице просматриваемого товара
  
  
